#model_path_mixtral: ./model/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
model_path_mixtral: ./model/mixtral-8x7b-instruct-v0.1.Q6_K.gguf
model_path_noromaid1: ./model/Noromaid-v0.1-mixtral-8x7b-Instruct-v3.q6_k.gguf
#model_path_noromaid1: ./model/Noromaid-v0.1-mixtral-8x7b-Instruct-v3.q4_k_m.gguf
model_path_noromaid4: ./model/noromaid-v0.4-mixtral-instruct-8x7b-zloss.Q6_K.gguf
template_prompt_mixtral: "[INST]{prompt}[/INST]{result}</s>"
template_prompt_noromaid1: "### Input:\n{prompt}\n\n### Response:\n{result}"
_selected_model: mixtral
__selected_model: noromaid1
selected_model: noromaid1
story: storyideas/gpt_example.yaml
rebuild: False
non_story_temperature: 0.4